[cmake]
version = "3.15"
cmkr-include = "cmake/cmkr.cmake"

[project]
name = "vcpkg_template"

[fetch-content]
cmkr-issue-repoA = { git = "https://github.com/darknessxk/cmkr-issue-repoA.git" }

# See https://github.com/microsoft/vcpkg#getting-started on how to use vcpkg
# Chose a version from https://github.com/microsoft/vcpkg/releases
# During CMake configuration you will be told how to find and link to the packages
[vcpkg]
version = "2020.11"
packages = ["fmt", "sqlite3"]

[find-package]
fmt = { version = "*" }
unofficial-sqlite3 = { version = "*" }

[target.example]
type = "executable"
sources = ["src/example.cpp"]
link-libraries = ["fmt::fmt", "unofficial::sqlite3::sqlite3"]